# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - fairino3_controller
<<<<<<< HEAD
    - sync_table2_controller
=======
>>>>>>> 283bdb1ee8ab1ba60250def566606a6668c2fdaf

  fairino3_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - j1
      - j2
      - j3
      - j4
      - j5
      - j6
    action_ns: follow_joint_trajectory
<<<<<<< HEAD
    default: true

  sync_table2_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: false
    joints:
      - sync_table2_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
=======
    default: true
>>>>>>> 283bdb1ee8ab1ba60250def566606a6668c2fdaf
